spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWKS_URL:}
  main:
    banner-mode: "off"
  sql:
    init:
      platform: "postgres"
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: "create" #необходимо для создания индексов
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: "true"
  servlet:
    multipart:
      max-file-size: "200MB"
      max-request-size: "220MB"
      file-size-threshold: "2KB"
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        #debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
